modLoader = "javafml"
loaderVersion = "[34,)"
license = "LGPLv3"
issueTrackerURL="https://github.com/dimadencep/sodium-extra-forge/issues"

[[mods]]
modId = "sodiumextra"
version = "${version}"
displayName = "Rubidium Extra"
updateJSONURL="https://api.modrinth.com/updates/rubidium-extra/forge_updates.json"
logoFile= "icon.png"
authors = "FlashyReese, dima_dencep"
displayURL = "https://github.com/dimadencep/sodium-extra-forge"
description = "Features that shouldn't be in Sodium."

[[dependencies.sodiumextra]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sodiumextra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sodiumextra]]
modId = "rubidium"
mandatory = true
versionRange = "[0.2.10,)"
ordering = "NONE"
side = "BOTH"