modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/dimadencep/sodium-extra-forge/issues"

[[mods]]
modId = "sodiumextra"
version = "${version}"
displayName = "Rubidium Extra"
logoFile= "icon.png"
updateJSONURL = "https://api.modrinth.com/updates/rubidium-extra/forge_updates.json"
authors = "dima_dencep, FlashyReese"
credits = "AMereBagatelle, DragonEggBedrockBreaking, EatMyVenom, HarvelsX, Kichura, Madis0, Paint_Ninja"
displayURL = "https://modrinth.com/mod/rubidium-extra"
description = "Features that shouldn't be in Rubidium."

[[dependencies.sodiumextra]]
modId = "rubidium"
mandatory = true
versionRange = "[0.6.2b,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.sodiumextra]]
modId = "caffeineconfig"
mandatory = true
versionRange = "[1.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.sodiumextra]]
modId = "minecraft" # Gives a friendlier error message when installed on the wrong MC version
mandatory = true
versionRange = "1.19.2"
ordering = "NONE"
side = "CLIENT"
