modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPLv3"
issueTrackerURL="https://github.com/dimadencep/sodium-extra-forge/issues"

[[mods]]
modId = "sodiumextra"
version = "${version}"
displayName = "Rubidium Extra"
logoFile= "icon.png"
updateJSONURL="https://api.modrinth.com/updates/rubidium-extra/forge_updates.json"
authors = "FlashyReese, dima_dencep"
displayURL = "https://github.com/dimadencep/sodium-extra-forge"
description = "Features that shouldn't be in Sodium."

[[dependencies.sodiumextra]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sodiumextra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sodiumextra]]
modId = "caffeineconfig"
mandatory = true
versionRange = "[1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sodiumextra]]
modId = "rubidium"
mandatory = true
versionRange = "[0.6.2,)"
ordering = "NONE"
side = "BOTH"