name: Publish Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradle
        id: build
        run: chmod +x gradlew && ./gradlew build
        
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "0.4.6.${{ github.run_number }}"
          prerelease: false
          title: "Rubidium-extra 0.4.6.${{ github.run_number }}"
          files: |
            build/libs/*

      - name: Publish to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          modrinth-id: oY2B1pjg
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 654373
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          version-type: release

          loaders: forge

          game-versions: |
            1.19
            1.19.1
          
          dependencies: |
            rubidium | depends | *
            oculus | recommends | *
            
          java: |
            17