name: Publish Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources

        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew
      - name: Upload assets to releases
        run: ./gradlew build publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          BUILD_RELEASE: ${{ github.event.prerelease == false }}
      - name: Publish to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: oY2B1pjg
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 654373
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          version-type: release

          loaders: forge

          game-versions: |
            1.19.2
          
          dependencies: |
            rubidium | depends | *
            textrues-rubidium-options | recommends | *
            oculus | recommends | *
            
          java: |
            17
